/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./components/layout/AppBreadcrumb.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    AppTopbar: typeof import('./components/layout/AppTopbar.vue')['default']
    AsyncPageState: typeof import('./components/common/AsyncPageState.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    FollowUpFormDialog: typeof import('./components/followups/FollowUpFormDialog.vue')['default']
    FollowUpList: typeof import('./components/followups/FollowUpList.vue')['default']
    LeadBoardCard: typeof import('./components/leads/LeadBoardCard.vue')['default']
    LeadBoardColumn: typeof import('./components/leads/LeadBoardColumn.vue')['default']
    LeadFilterPanel: typeof import('./components/leads/LeadFilterPanel.vue')['default']
    LeadFormDialog: typeof import('./components/leads/LeadFormDialog.vue')['default']
    LeadInfoCard: typeof import('./components/leads/LeadInfoCard.vue')['default']
    LeadStatusDialog: typeof import('./components/leads/LeadStatusDialog.vue')['default']
    LeadStatusTag: typeof import('./components/leads/LeadStatusTag.vue')['default']
    LeadTable: typeof import('./components/leads/LeadTable.vue')['default']
    LeadTagList: typeof import('./components/leads/LeadTagList.vue')['default']
    LeadTimeline: typeof import('./components/leads/LeadTimeline.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    PaginationBar: typeof import('./components/common/PaginationBar.vue')['default']
    RoutePlaceholder: typeof import('./components/common/RoutePlaceholder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
